name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    permissions:
      contents: write
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build TreeCuter
        run: ./gradlew build

      - name: Prepare release notes and artifacts
        run: |
          chmod +x ./scripts/prepareRelease.sh
          ./scripts/prepareRelease.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

      - name: Upload TreeCuter
        uses: actions/upload-artifact@main
        with:
          name: TreeCuter 1.9.2
          path: ./build/libs/TreeCuter-v1.9.2.jar

      - name: Release TreeCuter
        uses: softprops/action-gh-release@master
        with:
          name: "🌳 TreeCuter build ${{ env.BUILD_NUMBER }}"
          tag_name: "1.9.2"
          files: |
            ./build/libs/TreeCuter-v1.9.2.jar
          body_path: "./RELEASE.md"
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_commitish: "${{ github.sha }}"
          draft: false
          prerelease: false